import type { ReimbursementRule } from "./types";

export const DEFAULT_RULES: Omit<ReimbursementRule, "id">[] = [
  {
    key: "mileage_rate",
    name: "Mileage Rate",
    description: "Official rate per kilometer",
    type: "rate",
    value: 5.42,
    unit: "TRY/km",
    active: true,
  },
  {
    key: "communication_cap",
    name: "Communication Monthly Cap",
    description: "Maximum monthly reimbursement for phone and internet",
    type: "cap",
    value: 500,
    unit: "TRY",
    active: true,
  },
  {
    key: "hospitality_cap",
    name: "Hospitality Monthly Cap",
    description: "Maximum monthly reimbursement for hospitality/table costs",
    type: "cap",
    value: 2000,
    unit: "TRY",
    active: true,
  },
  {
    key: "utilities_percentage",
    name: "Utilities Reimbursement Percentage",
    description: "Percentage of utility bills eligible for reimbursement",
    type: "percentage",
    value: 50,
    unit: "%",
    active: true,
  },
  {
    key: "receipt_min_amount",
    name: "Receipt Required Minimum Amount",
    description: "Receipt required for expenses above this amount",
    type: "limit",
    value: 100,
    unit: "TRY",
    active: true,
  },
  {
    key: "expense_age_limit",
    name: "Expense Age Limit",
    description: "Maximum age of expense in days for reimbursement",
    type: "days",
    value: 90,
    unit: "days",
    active: true,
  },
  {
    key: "max_expense_amount",
    name: "Maximum Single Expense Amount",
    description: "Maximum reimbursable amount for a single expense",
    type: "cap",
    value: 10000,
    unit: "TRY",
    active: true,
  },
  {
    key: "rent_cap",
    name: "Rent Assistance Cap",
    description: "Maximum monthly rent assistance",
    type: "cap",
    value: 3000,
    unit: "TRY",
    active: true,
  },
];
